router id 10.0.0.2;

log "bird.log" all;

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    interface "lo";
}

protocol static static_route {
    ipv4;
    route 10.51.51.0/24 unreachable;
}

protocol static static_w_comms {
    ipv4;
    route 10.52.52.0/24 unreachable;
}

protocol bgp peer1 {
    local 10.0.0.2 as 64512;
    neighbor 10.0.0.3 as 64513;
    direct;
    ipv4 {
        import all;
        export filter {
            if proto = "static_w_comms" then {
                bgp_community.add((64512,1));
            }
            accept;
        };
    };
}
