neighbor 10.0.0.2 {
    peer-as 64512;
    router-id 10.0.0.3;
    local-address 10.0.0.3;
    local-as 64513;

    capability {
        asn4;
        route-refresh;
        graceful-restart;
    }

    api {
        processes [route-announce];
        neighbor-changes;
        receive {
            parsed;
            update;
            notification;
        }
    }
}

process route-announce {
    run ./main.py;
    encoder json;
}
