SMTP_SERVER = "YOUR_SMTP_SERVER_HERE"
SMTP_PORT = "YOUR_SMTP_PORT_HERE" # must be a integer like SMTP_PORT = 587
SMTP_USER = "YOUR_SMTP_USER_HERE"
SMTP_PASS = "YOUR_SMTP_PASS_HERE"
SENDER = f"CHANGE_FOR_THE_USER_TO_APPEAR <{SMTP_USER}>" # something like SENDER = f"Equipe GT Crivo <{SMTP_USER}>"
USERS_FILE = "users_emails_list.txt"
REPORT_FILES = "REPORTS_PATH"
